# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# GitHub recommends pinning actions to a commit SHA.
# To get a newer version, you will need to update the SHA.
# You can also reference a tag or branch, but the action may change without warning.

name: Publish Docker image

on:
  release:
    types: [published]

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    steps:
      - name: Check out the repo
        uses: actions/checkout@v6

      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"

      - name: Extract metadata (tags, labels) for Docker System-Development
        id: meta_sysdev_image
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: is140608/sys_devel_env
          tags: |
            type=ref,event=branch
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
          labels: |
            org.opencontainers.image.created={{date 'YYYY-MM-DD'}}
            org.opencontainers.image.revision=${{ github.sha }}

      - name: Build and push Docker System-Development image
        id: push_sysdev_image
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          file: ./system_development/Dockerfile
          push: true
          tags: ${{ steps.meta_sysdev_image.outputs.tags }}
          labels: ${{ steps.meta_sysdev_image.outputs.labels }}

      - name: Generate artifact attestation
        uses: actions/attest@v4
        with:
          subject-name: index.docker.io/is140608/sys_devel_env
          subject-digest: ${{ steps.push_sysdev_image.outputs.digest }}
          push-to-registry: true



      - name: Extract metadata (tags, labels) for Docker Codex IDE
        id: meta_codexide_image
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: is140608/codex_ide_env
          tags: |
            type=ref,event=branch
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
          labels: |
            org.opencontainers.image.created={{date 'YYYY-MM-DD'}}
            org.opencontainers.image.revision=${{ github.sha }}

      - name: Build and push Docker Codex IDE image
        id: push_codexide_image
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          file: ./system_development/ai_pow_development/codex_ide/Dockerfile
          push: true
          tags: ${{ steps.meta_codexide_image.outputs.tags }}
          labels: ${{ steps.meta_codexide_image.outputs.labels }}

      - name: Generate artifact attestation
        uses: actions/attest@v4
        with:
          subject-name: index.docker.io/is140608/codex_ide_env
          subject-digest: ${{ steps.push_codexide_image.outputs.digest }}
          push-to-registry: true



      - name: Extract metadata (tags, labels) for Docker Cursor IDE
        id: meta_cursorxide_image
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: is140608/cursor_ide_env
          tags: |
            type=ref,event=branch
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
          labels: |
            org.opencontainers.image.created={{date 'YYYY-MM-DD'}}
            org.opencontainers.image.revision=${{ github.sha }}

      - name: Build and push Docker Cursor IDE image
        id: push_cursoride_image
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          file: ./system_development/ai_pow_development/cursor_ide/Dockerfile
          push: true
          tags: ${{ steps.meta_cursorxide_image.outputs.tags }}
          labels: ${{ steps.meta_cursorxide_image.outputs.labels }}

      - name: Generate artifact attestation
        uses: actions/attest@v4
        with:
          subject-name: index.docker.io/is140608/cursor_ide_env
          subject-digest: ${{ steps.push_cursoride_image.outputs.digest }}
          push-to-registry: true
